version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: ""
  enableJavascript: true
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 750
  launch-options:
    headless: false
  disableCache: false
  concurrency: 1
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
