version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  minHeight: 1024
  #percyCSS: ".change-font{display: none;} .fixed-header{display: none;}"
discovery:
  allowedHostnames: ["*.devs.rnd.live.backbaseservices.com", "ui-ang-showcase-app.devs.rnd.live.backbaseservices.com"]
  disallowedHostnames: []
  networkIdleTimeout: 750
  launch-options:
    headless: false
  disableCache: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
