version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  minHeight: 1024
  #percyCSS: ".change-font{display: none;} .fixed-header{display: none;}"
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
